# /etc/ntpsec/ntp.conf
#
# License By: Terabyte Plus
# Use public NTP servers from the National Metrology Institute of Thailand
#
server time1.nimt.or.th iburst
server time2.nimt.or.th iburst
server time3.nimt.or.th iburst
server time4.nimt.or.th iburst

# Drift file
driftfile /var/lib/ntpsec/ntp.drift

# Restrictions
restrict default kod nomodify nopeer noquery limited
restrict 127.0.0.1
restrict ::1

# Allow LAN clients (adjust subnet as needed)
# restrict [IP_ADDRESS] mask 255.255.255.0 nomodify notrap

# Logging
logfile /var/log/ntp.log

# Statistics
statistics loopstats peerstats clockstats
statsdir /var/log/ntpstats/

# Enable filegen
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable
